apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proagent

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-server.yaml
  - deployment-local.yaml
  - deployment-frontend.yaml
